### PR TITLE
Added support for pt3 files

### PR DESCRIPTION
**Pull request by talaurence**
Added support for pt3 files following the example of ht3

### CODE REVIEW

**Comment by tritemio** [comment]
Received, let me take a look. 

xref: This PR addresses #13.

**Comment by tritemio** [comment]
By looking at it, it looks very good! I noticed you fixed a few typos and added some forgotten fields to the metadata, good catch! Thanks.

I'd like to run it on a test file before merging. Can you upload send me a sample test file that we can later include in phconvert example data files?

Later (another PR) we should also add a notebook to convert PT3 files. It should be a trivial modification from the HT3 notebook.

**Comment by talaurence** [comment]
Attached is a short file that you can use.  If you plot a time trace you see a periodic signal.  It is rather boring, and there is no actual lifetime information, but it can show you how it works.

I probably wouldn’t want to post this data to a web site, but you can take a look at it.

-Ted

**Comment by tritemio** [comment]
Attaching files through github does not work, sorry, you can send me a private email. We need a dummy file that we can use for testing and to build a runnable notebook that a user can take and use with its own files by simply changing the file name. I doesn't need to be "interesting" data.

**Comment by tritemio** [comment]
Ok, I tested it with a PT3 file downloaded from https://github.com/paulmueller/FCS_point_correlator and it works as expected, merging.

**Pull request merged**
