### PR TITLE
Support SPC-1xx/830

### PR DESCRIPTION
**Pull request by lampo808**
Rebased on the latest commit

### CODE REVIEW

**Comment by tritemio** [comment]
Looks good, thanks! 

I'm merging it, then I'll fix some docs and release 0.7.1 with your changes. The next phconvert major version (maybe it will jump to 1.0) it will support the [new Photon-HDF5 0.5](https://github.com/Photon-HDF5/photon-hdf5/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.5), but it will still take some time to complete. In the meanwhile 0.7.1 will make your additions available to everybody.

**Comment by tritemio** [comment]
@lampo808, please send me the name and other info (like affiliation, ORCID, whatever you prefer) you want me to use for the Authors/Contributors section.

**Comment by tritemio** [comment]
FYI, the latest version of phconvert can be installed from the [conda-forge](https://conda-forge.github.io/) channel:

```
conda install phconvert -c conda-forge
```

Previously it was in my own channel (`tritemio`). But conda-forge automatically builds the packages for all the platforms for me.

**Comment by lampo808** [comment]
@tritemio here are the infos:
name: Marco Lamperti
email: m dot lamperti1 at uninsubria dot it
affiliation: University of Insubria (Como, Italy)
ORCID: 0000-0001-5972-8723

**Pull request merged**
